SCR_EntityCatalogMultiList {
 m_aMultiLists {
  SCR_EntityCatalogMultiListEntry "{B70500000000B001}" {
   m_sIdentifier "Bookshelf Utility"
   m_aEntities {
    SCR_EntityCatalogInventoryItem "{B70500000000B002}" {
     m_sEntityPrefab "{13772C903CB5E4F7}Prefabs/Items/Equipment/Maps/Map_Paper_01/PaperMap_01_folded.et"
     m_aEntityDataList {
      FM_ArsenalItem "{B70500000000B003}" {
       m_eItemType EQUIPMENT
       m_iSupplyCost 3
       m_iMinSpawn 0
      }
     }
    }
    SCR_EntityCatalogInventoryItem "{B70500000000B004}" {
     m_sEntityPrefab "{61A705D76908160C}Prefabs/Items/Equipment/Watches/Watch_Orlik38/Watch_Orlik38.et"
     m_aEntityDataList {
      FM_ArsenalItem "{B70500000000B005}" {
       m_eItemType EQUIPMENT
       m_iSupplyCost 3
       m_iMinSpawn 0
      }
     }
    }
    SCR_EntityCatalogInventoryItem "{B70500000000B006}" {
     m_sEntityPrefab "{61D4F80E49BF9B12}Prefabs/Items/Equipment/Compass/Compass_SY183.et"
     m_aEntityDataList {
      FM_ArsenalItem "{B70500000000B007}" {
       m_eItemType EQUIPMENT
       m_iSupplyCost 4
       m_iMinSpawn 0
      }
     }
    }
   }
  }
 }
}
