SCR_EntityCatalogMultiList {
 m_aMultiLists {
  SCR_EntityCatalogMultiListEntry "{B705000000002001}" {
   m_sIdentifier "Cardboard Box Civil"
   m_aEntities {
    SCR_EntityCatalogInventoryItem "{B705000000002002}" {
     m_sEntityPrefab "{0A13D9E72CF41133}Prefabs/FoodDrink/MRE.et"
     m_aEntityDataList {
      FM_ArsenalItem "{B705000000002003}" {
       m_eItemType FOOD
       m_iSupplyCost 3
       m_iMinSpawn 0
      }
     }
    }
    SCR_EntityCatalogInventoryItem "{B705000000002004}" {
     m_sEntityPrefab "{1C56106978CD7B60}Prefabs/FoodDrink/CannedFood.et"
     m_aEntityDataList {
      FM_ArsenalItem "{B705000000002005}" {
       m_eItemType FOOD
       m_iSupplyCost 2
       m_iMinSpawn 0
      }
     }
    }
    SCR_EntityCatalogInventoryItem "{B705000000002006}" {
     m_sEntityPrefab "{619D10551472D7DC}Prefabs/FoodDrink/Apple.et"
     m_aEntityDataList {
      FM_ArsenalItem "{B705000000002007}" {
       m_eItemType FOOD
       m_iSupplyCost 1
       m_iMinSpawn 0
      }
     }
    }
    SCR_EntityCatalogInventoryItem "{B705000000002008}" {
     m_sEntityPrefab "{610CFCE348C1782F}Prefabs/FoodDrink/Pear.et"
     m_aEntityDataList {
      FM_ArsenalItem "{B705000000002009}" {
       m_eItemType FOOD
       m_iSupplyCost 1
       m_iMinSpawn 0
      }
     }
    }
    SCR_EntityCatalogInventoryItem "{B70500000000200A}" {
     m_sEntityPrefab "{D7DC4E6EE61E99C1}Prefabs/Props/Furniture/RequiredItems/ToolKit.et"
     m_aEntityDataList {
      FM_ArsenalItem "{B70500000000200B}" {
       m_eItemType BUILD
       m_iSupplyCost 5
       m_iMinSpawn 0
      }
     }
    }
   }
  }
 }
}
