SCR_EntityCatalogMultiList {
 m_aMultiLists {
  SCR_EntityCatalogMultiListEntry "{B70500000000A001}" {
   m_sIdentifier "Civil Desk"
   m_aEntities {
    SCR_EntityCatalogInventoryItem "{B70500000000A002}" {
     m_sEntityPrefab "{6BADCDCC0DFE2401}Prefabs/Items/Medicine/FieldDressing_01/Bandage.et"
     m_aEntityDataList {
      FM_ArsenalItem "{B70500000000A003}" {
       m_eItemType HEAL
       m_eItemMode CONSUMABLE
       m_iSupplyCost 1
       m_iMinSpawn 0
      }
     }
    }
    SCR_EntityCatalogInventoryItem "{B70500000000A004}" {
     m_sEntityPrefab "{575EA58E67448C2A}Prefabs/Items/Equipment/Flashlights/Flashlight_Soviet_01/Flashlight_Soviet_01.et"
     m_aEntityDataList {
      FM_ArsenalItem "{B70500000000A005}" {
       m_eItemType EQUIPMENT
       m_iSupplyCost 2
       m_iMinSpawn 0
      }
     }
    }
    SCR_EntityCatalogInventoryItem "{B70500000000A006}" {
     m_sEntityPrefab "{61D4F80E49BF9B12}Prefabs/Items/Equipment/Compass/Compass_SY183.et"
     m_aEntityDataList {
      FM_ArsenalItem "{B70500000000A007}" {
       m_eItemType EQUIPMENT
       m_iSupplyCost 4
       m_iMinSpawn 0
      }
     }
    }
    SCR_EntityCatalogInventoryItem "{B70500000000A008}" {
     m_sEntityPrefab "{61A705D76908160C}Prefabs/Items/Equipment/Watches/Watch_Orlik38/Watch_Orlik38.et"
     m_aEntityDataList {
      FM_ArsenalItem "{B70500000000A009}" {
       m_eItemType EQUIPMENT
       m_iSupplyCost 3
       m_iMinSpawn 0
      }
     }
    }
   }
  }
 }
}
