SCR_EntityCatalogMultiList {
 m_aMultiLists {
  SCR_EntityCatalogMultiListEntry "{B705000000006001}" {
   m_sIdentifier "Freezer Food"
   m_aEntities {
    SCR_EntityCatalogInventoryItem "{B705000000006002}" {
     m_sEntityPrefab "{8B3A6788BF261FDA}Prefabs/FoodDrink/DryMeat.et"
     m_aEntityDataList {
      FM_ArsenalItem "{B705000000006003}" {
       m_eItemType FOOD
       m_iSupplyCost 2
       m_iMinSpawn 0
      }
     }
    }
    SCR_EntityCatalogInventoryItem "{B705000000006004}" {
     m_sEntityPrefab "{2D4D209BE5B92DA6}Prefabs/FoodDrink/Cheese.et"
     m_aEntityDataList {
      FM_ArsenalItem "{B705000000006005}" {
       m_eItemType FOOD
       m_iSupplyCost 2
       m_iMinSpawn 0
      }
     }
    }
    SCR_EntityCatalogInventoryItem "{B705000000006006}" {
     m_sEntityPrefab "{5DC18BFBAA93C151}Prefabs/FoodDrink/Blueberry.et"
     m_aEntityDataList {
      FM_ArsenalItem "{B705000000006007}" {
       m_eItemType FOOD
       m_iSupplyCost 1
       m_iMinSpawn 0
      }
     }
    }
    SCR_EntityCatalogInventoryItem "{B705000000006008}" {
     m_sEntityPrefab "{7247A8706B43BC8C}Prefabs/FoodDrink/Cherry.et"
     m_aEntityDataList {
      FM_ArsenalItem "{B705000000006009}" {
       m_eItemType FOOD
       m_iSupplyCost 1
       m_iMinSpawn 0
      }
     }
    }
   }
  }
 }
}
