SCR_EntityCatalogMultiList {
 m_aMultiLists {
  SCR_EntityCatalogMultiListEntry "{B705000000003001}" {
   m_sIdentifier "Kitchen Food"
   m_aEntities {
    SCR_EntityCatalogInventoryItem "{B705000000003002}" {
     m_sEntityPrefab "{1C56106978CD7B60}Prefabs/FoodDrink/CannedFood.et"
     m_aEntityDataList {
      FM_ArsenalItem "{B705000000003003}" {
       m_eItemType FOOD
       m_iSupplyCost 2
      }
     }
    }
    SCR_EntityCatalogInventoryItem "{B705000000003004}" {
     m_sEntityPrefab "{2DA40953CC5C6D88}Prefabs/FoodDrink/WaterBottler.et"
     m_aEntityDataList {
      FM_ArsenalItem "{B705000000003005}" {
       m_eItemType FOOD
       m_iSupplyCost 2
      }
     }
    }
    SCR_EntityCatalogInventoryItem "{B705000000003006}" {
     m_sEntityPrefab "{619D10551472D7DC}Prefabs/FoodDrink/Apple.et"
     m_aEntityDataList {
      FM_ArsenalItem "{B705000000003007}" {
       m_eItemType FOOD
       m_iSupplyCost 1
      }
     }
    }
    SCR_EntityCatalogInventoryItem "{B705000000003008}" {
     m_sEntityPrefab "{610CFCE348C1782F}Prefabs/FoodDrink/Pear.et"
     m_aEntityDataList {
      FM_ArsenalItem "{B705000000003009}" {
       m_eItemType FOOD
       m_iSupplyCost 1
      }
     }
    }
    SCR_EntityCatalogInventoryItem "{B70500000000300A}" {
     m_sEntityPrefab "{2D4D209BE5B92DA6}Prefabs/FoodDrink/Cheese.et"
     m_aEntityDataList {
      FM_ArsenalItem "{B70500000000300B}" {
       m_eItemType FOOD
       m_iSupplyCost 2
      }
     }
    }
    SCR_EntityCatalogInventoryItem "{B70500000000300C}" {
     m_sEntityPrefab "{9520DCEB37454656}Prefabs/FoodDrink/Beer.et"
     m_aEntityDataList {
      FM_ArsenalItem "{B70500000000300D}" {
       m_eItemType FOOD
       m_iSupplyCost 3
      }
     }
    }
   }
  }
 }
}
