SCR_EntityCatalogMultiList {
 m_aMultiLists {
  SCR_EntityCatalogMultiListEntry "{B705000000005001}" {
   m_sIdentifier "Industrial Stove Food"
   m_aEntities {
    SCR_EntityCatalogInventoryItem "{B705000000005002}" {
     m_sEntityPrefab "{0A13D9E72CF41133}Prefabs/FoodDrink/MRE.et"
     m_aEntityDataList {
      FM_ArsenalItem "{B705000000005003}" {
       m_eItemType FOOD
       m_iSupplyCost 3
      }
     }
    }
    SCR_EntityCatalogInventoryItem "{B705000000005004}" {
     m_sEntityPrefab "{1C56106978CD7B60}Prefabs/FoodDrink/CannedFood.et"
     m_aEntityDataList {
      FM_ArsenalItem "{B705000000005005}" {
       m_eItemType FOOD
       m_iSupplyCost 2
      }
     }
    }
    SCR_EntityCatalogInventoryItem "{B705000000005006}" {
     m_sEntityPrefab "{2DA40953CC5C6D88}Prefabs/FoodDrink/WaterBottler.et"
     m_aEntityDataList {
      FM_ArsenalItem "{B705000000005007}" {
       m_eItemType FOOD
       m_iSupplyCost 2
      }
     }
    }
    SCR_EntityCatalogInventoryItem "{B705000000005008}" {
     m_sEntityPrefab "{9A749EFD428F969F}Prefabs/FoodDrink/Vodka.et"
     m_aEntityDataList {
      FM_ArsenalItem "{B705000000005009}" {
       m_eItemType FOOD
       m_iSupplyCost 4
      }
     }
    }
   }
  }
 }
}
