SCR_EntityCatalogMultiList {
 m_aMultiLists {
  SCR_EntityCatalogMultiListEntry "{B705000000001001}" {
   m_sIdentifier "Suitcase Civil Small"
   m_aEntities {
    SCR_EntityCatalogInventoryItem "{B705000000001002}" {
     m_sEntityPrefab "{61A705D76908160C}Prefabs/Items/Equipment/Watches/Watch_Orlik38/Watch_Orlik38.et"
     m_aEntityDataList {
      FM_ArsenalItem "{B705000000001003}" {
       m_eItemType EQUIPMENT
       m_iSupplyCost 3
       m_iMinSpawn 0
      }
     }
    }
    SCR_EntityCatalogInventoryItem "{B705000000001004}" {
     m_sEntityPrefab "{575EA58E67448C2A}Prefabs/Items/Equipment/Flashlights/Flashlight_Soviet_01/Flashlight_Soviet_01.et"
     m_aEntityDataList {
      FM_ArsenalItem "{B705000000001005}" {
       m_eItemType EQUIPMENT
       m_iSupplyCost 2
       m_iMinSpawn 0
      }
     }
    }
    SCR_EntityCatalogInventoryItem "{B705000000001006}" {
     m_sEntityPrefab "{61D4F80E49BF9B12}Prefabs/Items/Equipment/Compass/Compass_SY183.et"
     m_aEntityDataList {
      FM_ArsenalItem "{B705000000001007}" {
       m_eItemType EQUIPMENT
       m_iSupplyCost 4
       m_iMinSpawn 0
      }
     }
    }
    SCR_EntityCatalogInventoryItem "{B705000000001008}" {
     m_sEntityPrefab "{6BADCDCC0DFE2401}Prefabs/Items/Medicine/FieldDressing_01/Bandage.et"
     m_aEntityDataList {
      FM_ArsenalItem "{B705000000001009}" {
       m_eItemType HEAL
       m_eItemMode CONSUMABLE
       m_iSupplyCost 1
       m_iMinSpawn 0
      }
     }
    }
   }
  }
 }
}
