SCR_EntityCatalogMultiList {
 m_aMultiLists {
  SCR_EntityCatalogMultiListEntry "{B705000000008001}" {
   m_sIdentifier "Tool Box"
   m_aEntities {
    SCR_EntityCatalogInventoryItem "{B705000000008002}" {
     m_sEntityPrefab "{05562DD0D7651987}Prefabs/Items/Equipment/Kits/RepairKit_01/RepairKitFM.et"
     m_aEntityDataList {
      FM_ArsenalItem "{B705000000008003}" {
       m_eItemType TOOLS
       m_iSupplyCost 3
       m_iMinSpawn 0
      }
     }
    }
    SCR_EntityCatalogInventoryItem "{B705000000008004}" {
     m_sEntityPrefab "{D7DC4E6EE61E99C1}Prefabs/Props/Furniture/RequiredItems/ToolKit.et"
     m_aEntityDataList {
      FM_ArsenalItem "{B705000000008005}" {
       m_eItemType BUILD
       m_iSupplyCost 5
       m_iMinSpawn 0
      }
     }
    }
    SCR_EntityCatalogInventoryItem "{B705000000008006}" {
     m_sEntityPrefab "{575EA58E67448C2A}Prefabs/Items/Equipment/Flashlights/Flashlight_Soviet_01/Flashlight_Soviet_01.et"
     m_aEntityDataList {
      FM_ArsenalItem "{B705000000008007}" {
       m_eItemType EQUIPMENT
       m_iSupplyCost 2
       m_iMinSpawn 0
      }
     }
    }
    SCR_EntityCatalogInventoryItem "{B705000000008008}" {
     m_sEntityPrefab "{27FCA0F311B3559C}Prefabs/Weapons/Attachments/Flashlight/Tapelight.et"
     m_aEntityDataList {
      FM_ArsenalItem "{B705000000008009}" {
       m_eItemType EQUIPMENT
       m_iSupplyCost 3
       m_iMinSpawn 0
      }
     }
    }
    SCR_EntityCatalogInventoryItem "{B70500000000800A}" {
     m_sEntityPrefab "{E7DF31108D38A8A8}Prefabs/Items/Fuel/Jerrycan_01/Jerrycan_01_item_base.et"
     m_aEntityDataList {
      FM_ArsenalItem "{B70500000000800B}" {
       m_eItemType VEHICLE
       m_iSupplyCost 5
       m_iMinSpawn 0
      }
     }
    }
   }
  }
 }
}
