SCR_EntityCatalogMultiList {
 m_aMultiLists {
  SCR_EntityCatalogMultiListEntry "{B705000000009001}" {
   m_sIdentifier "Wardrobe Clothing"
   m_aEntities {
    SCR_EntityCatalogInventoryItem "{B705000000009002}" {
     m_sEntityPrefab "{DD565E2C7E00A5BB}Prefabs/Characters/HeadGear/Hat_FlatCap_01/Hat_FlatCap_01_blue.et"
     m_aEntityDataList {
      FM_ArsenalItem "{B705000000009003}" {
       m_eItemType HEADWEAR
       m_iSupplyCost 1
      }
     }
    }
    SCR_EntityCatalogInventoryItem "{B705000000009004}" {
     m_sEntityPrefab "{BE19A15F1073E7BD}Prefabs/Characters/HeadGear/Hat_Knitted_01/Hat_Knitted_01_black.et"
     m_aEntityDataList {
      FM_ArsenalItem "{B705000000009005}" {
       m_eItemType HEADWEAR
       m_iSupplyCost 1
      }
     }
    }
    SCR_EntityCatalogInventoryItem "{B705000000009006}" {
     m_sEntityPrefab "{BBA08EC4EC40FA94}Prefabs/Characters/Uniforms/Jacket_M70.et"
     m_aEntityDataList {
      FM_ArsenalItem "{B705000000009007}" {
       m_eItemType TORSO
       m_iSupplyCost 2
      }
     }
    }
    SCR_EntityCatalogInventoryItem "{B705000000009008}" {
     m_sEntityPrefab "{06BC3F18B47799AE}Prefabs/Characters/Uniforms/Pants_M70.et"
     m_aEntityDataList {
      FM_ArsenalItem "{B705000000009009}" {
       m_eItemType LEGS
       m_iSupplyCost 2
      }
     }
    }
    SCR_EntityCatalogInventoryItem "{B70500000000900A}" {
     m_sEntityPrefab "{12321B761A982B49}Prefabs/Items/Equipment/Backpacks/Small Gun Bag.et"
     m_aEntityDataList {
      FM_ArsenalItem "{B70500000000900B}" {
       m_eItemType BACKPACK
       m_iSupplyCost 6
      }
     }
    }
   }
  }
 }
}
