ADM_ShopCategory {
 m_DisplayName "Civilian Helicopters"
 m_Items {
  "{7A29940A71EF5F5C}Prefabs/Vehicles/Helicopters/UH1H/UH1H_civ_livery_v1.et"
  "{8175FCADFA2FB904}Prefabs/Vehicles/Helicopters/Mi8MT/Mi8MT_unarmed_civ_red.et"
  "{AF950919C81D91B4}Prefabs/Vehicles/Helicopters/AH6M/MH6M.et"
 }
}
