ADM_ShopCategory {
 m_DisplayName "Attachments"
 m_Items {
  "{D92368B78263A9E0}Prefabs/Weapons/Attachments/Mounts/Dovetail_AK/Dovetail_AK.et"
  "{BBE1F3AD25BB00EF}Prefabs/Weapons/Attachments/RangeFinder/Radius_RangeFinder_RIS.et"
  "{C2AE7E78E486B183}Prefabs/Weapons/Attachments/Laser/LA5B_BLK.et"
  "{01D3CD96BB15916D}Prefabs/Weapons/Attachments/Laser/LA5B_TAN.et"
  "{297F6C33AF97B004}Prefabs/Weapons/Attachments/Laser/PEQ01_RIS.et"
  "{D74EB77B38A8C601}Prefabs/Weapons/Attachments/Laser/PEQ15_RIS.et"
  "{5FEB33C1600975AF}Prefabs/Weapons/Attachments/Flashlight/m500_black.et"
  "{A7B90CDB91BBA0E6}Prefabs/Weapons/Attachments/Flashlight/m600v_black.et"
  "{27FCA0F311B3559C}Prefabs/Weapons/Attachments/Flashlight/Tapelight.et"
  "{1878DA1F28BA6A92}Prefabs/Weapons/Attachments/Bipods/Leapers_UTG_360.et"
 }
}