ADM_ShopCategory {
 m_DisplayName "Handguns"
 m_Items {
  "{1353C6EAD1DCFE43}Prefabs/Handguns/M9/Handgun_M9.et"
  "{C0F7DD85A86B2900}Prefabs/Handguns/PM/Handgun_PM.et"
  "{D8EDB21CBF9A9B65}Prefabs/Weapons/Handguns/PDW/Uzi.et"
  "{243255055CA82B13}Prefabs/Weapons/Handguns/Skorpion vz. 61/Skorpion vz. 61.et"
  "{BBFC0AF7B7714740}Prefabs/Weapons/Handguns/Pistols/Handgun_DesertEagle_base.et"
  "{F2353BE382A90821}Prefabs/Weapons/Handguns/M9/Handgun_Glock17_base.et"
  "{4BDA7F364D3FC8C1}Prefabs/Weapons/Rifles/ColtPython/Rifle_ColtPython.et"
  "{A77F06B892FA378B}Prefabs/Weapons/Handguns/BaconM17/Handgun_BaconM17.et"
  "{A535CFE4F80C88DF}Prefabs/BaconScorpion/SMG_Scorpion.et"
 }
}
