ADM_ShopCategory {
 m_DisplayName "Knives"
 m_Items {
  "{8E4663FD6B74BB57}Prefabs/Knifes/BayonetKnife/BayonetKnifeAC.et"
  "{2189664E08B26B2A}Prefabs/Knifes/ButterflyKnife/ButterflyKnifeAC.et"
  "{E5FF2886246E0797}Prefabs/Knifes/HuntsmanKnife/HuntsmanKnifeAC.et"
  "{49EAF95FBCF04EE8}Prefabs/Knifes/KarambitKnife/KarambitKnifeAC.et"
  "{4788E8C5C04D2A49}Prefabs/Weapons/Attachments/Bayonets/BC_Bayonet_Mosin.et"
  "{98C79F5FAE12F9B6}Prefabs/Weapons/Attachments/Bayonets/Bayonet_6Kh4.et"
  "{3F1B1BAD1F6DDC28}Prefabs/Weapons/Attachments/Bayonets/Bayonet_VZ58/Bayonet_VZ58_v1.et"
  "{558117556F3880A8}Prefabs/Weapons/Attachments/Bayonets/Bayonet_M9.et"
 }
}