ADM_ShopCategory {
 m_DisplayName "Night Vision"
 m_Items {
  "{04B842B21C00FA4D}Prefabs/Characters/Items/NVG/GPNVG_18_GP.et"
  "{098C6A2D8DA0CE83}Prefabs/Characters/Items/NVG/NVS_Headstrap.et"
  "{4801D21DAE00D59B}Prefabs/Characters/Items/NVG/PVS31-GP_Slotted.et"
  "{76E6160034F461FE}Prefabs/Characters/Items/NVG/PVS31-WP_Slotted.et"
 }
}
