ADM_ShopCategory {
 m_DisplayName "Rifles"
 m_Items {
  "{FA5C25BF66A53DCF}Prefabs/Weapons/Rifles/AK74/Rifle_AK74.et"
  "{63E8322E2ADD4AA7}Prefabs/Weapons/Rifles/AK74/Rifle_AK74_GP25.et"
  "{3E413771E1834D2F}Prefabs/Weapons/Rifles/M16/Rifle_M16A2.et"
  "{B1482FB64E3D2D45}Prefabs/Weapons/Rifles/M16/Rifle_M16A2_4x20.et"
  "{9C948630078D154D}Prefabs/Weapons/Rifles/VZ58/Rifle_VZ58P.et"
  "{443CEFF17E040B11}Prefabs/Weapons/Rifles/VZ58/Rifle_VZ58V.et"
  "{DD1BCD7922BBB516}Prefabs/Weapons/Rifles/Carl Gustaf M45/BC_Rifle_Carl_Gustaf_M45.et"
  "{AD1B343E015F2D11}Prefabs/Weapons/Rifles/M3A1/BC_M3A1.et"
  "{BFE79C383ABDE6D2}Prefabs/Weapons/Rifles/MP40/BC_MP40.et"
  "{6AA1C567A2F7F8CE}Prefabs/Weapons/Rifles/PPSH41/BC_PPSh41.et"
  "{E3E9CB8B5D3A37AB}Prefabs/Weapons/Rifles/Thompson M1928A1/BC_Rifle_Thompson_M1928A1.et"
  "{B6673927CF21BE87}Prefabs/Weapons/Rifles/Thompson M1A1/BC_Rifle_Thompson_M1A1.et"
  "{FD14223C1A75F9DE}Prefabs/Weapons/Rifles/m4a3/m4a3.et"
  "{755415E3E3DA9014}Prefabs/Weapons/Rifles/MK12 SPR/MK12 SPR.et"
 }
}