ADM_ShopCategory {
 m_DisplayName "Shotguns"
 m_Items {
  "{3D3758C525994D3A}Prefabs/Weapons/Shotguns/Double Barrel/BC_Shotgun_Double_Barrel_610mm.et"
  "{3C4FB3D9D54B46DF}Prefabs/Weapons/Shotguns/Double Barrel/BC_Shotgun_Double_Barrel_760mm.et"
  "{E7A3BA1F06C057FF}Prefabs/Weapons/Shotguns/Double Barrel/BC_Shotgun_Double_Barrel_Sawn_Off.et"
  "{9655CB851205DF47}Prefabs/Weapons/Shotguns/Ithaca 37/BC_Shotgun_Ithaca_37.et"
  "{34B2434D37E3FF16}Prefabs/Weapons/Shotguns/Ithaca 37/BC_Shotgun_Ithaca_37_Sawed.et"
  "{9E8405BDD24BCF69}Prefabs/Weapons/Shotguns/Ithaca 37/BC_Shotgun_Ithaca_37_V2.et"
  "{458A4E8CD3590D92}Prefabs/Weapons/Shotguns/Remington 870/BC_Shotgun_Remington_870.et"
  "{563C338A655857B7}Prefabs/Weapons/Shotguns/Remington 870/BC_Shotgun_Remington_870_V2.et"
  "{0E894FC29BFCC6F9}Prefabs/Weapons/Rifles/12Gauge/Shotgun_DracarysGen12_base.et"
 }
}
