ADM_ShopCategory {
 m_DisplayName "Snipers"
 m_Items {
  "{6FAB3F7925ED69BB}Prefabs/Weapons/Rifles/SVD/m14 dmr.et"
  "{16711482483C78BC}Prefabs/Weapons/Rifles/SVD/m14 dmr2.et"
  "{3EB02CDAD5F23C82}Prefabs/Weapons/Rifles/SVD/Rifle_SVD.et"
  "{6415B7923DE28C1B}Prefabs/Weapons/Rifles/SVD/Rifle_SVD_PSO.et"
  "{C1B4F7B87B720EE8}Prefabs/Weapons/Rifles/Mosin/BC_Rifle_Mosin_Nagant_9130.et"
  "{6545DEABED4759E5}Prefabs/Weapons/Rifles/Mosin/BC_Rifle_Mosin_Nagant_9130_PU.et"
  "{B31929F65F0D0279}Prefabs/Weapons/Rifles/M14/Rifle_M21.et"
  "{81EB948E6414BD6F}Prefabs/Weapons/Rifles/M14/Rifle_M21_ARTII.et"
 }
}