ADM_ShopCategory {
 m_DisplayName "Suppressors"
 m_Items {
  "{8231579E96735D40}Prefabs/Weapons/Attachments/Suppressor/BC_Suppressor_Bramit_Mosin.et"
  "{4AD93799EA5840F9}Prefabs/Weapons/Attachments/Muzzle/Suppressor_M16/308.et"
  "{62434798E2B08EBA}Prefabs/Weapons/Attachments/Suppressor/BC_Suppressor_M45.et"
  "{4308DBEE30E1A692}Prefabs/Attachments/Suppressor/Suppressor_M16/Suppressor_M16_base.et"
  "{5677861A692ED3EB}Prefabs/Attachments/Suppressor/Suppressor_PBS4/Suppressor_PBS4_base.et"
  "{87D2C9FC797832FB}Prefabs/Attachments/Suppressor/Suppressor_Pistol/Suppressor_Pistol.et"
 }
}