SCR_EntityCatalogMultiList {
 m_aMultiLists {
  SCR_EntityCatalogMultiListEntry "{68EEFCC184D40279}" {
   m_sIdentifier "Food"
   m_aEntities {
    SCR_EntityCatalogInventoryItem "{68EEFCC184D40270}" {
     m_sEntityPrefab "{619D10551472D7DC}Prefabs/FoodDrink/Apple.et"
     m_aEntityDataList {
      FM_ArsenalItem "{68EEFCC184D40272}" {
       m_eItemType FOOD
       m_iSupplyCost 1
       m_iMaxSpawn 2
      }
     }
    }
    SCR_EntityCatalogInventoryItem "{68F368FCD540239F}" {
     m_sEntityPrefab "{CAC078FA37D4C95C}Prefabs/Props/Furniture/RequiredItems/Leaves.et"
     m_aEntityDataList {
      FM_ArsenalItem "{68F32EE2B50F8E58}" {
       m_eItemType BUILD
       m_iSupplyCost 1
       m_iMinSpawn 5
       m_iMaxSpawn 10
      }
     }
    }
    SCR_EntityCatalogInventoryItem "{68F368FCD4995BCE}" {
     m_sEntityPrefab "{6FEC87C6B133A5F0}Prefabs/Props/Furniture/RequiredItems/stick.et"
     m_aEntityDataList {
      FM_ArsenalItem "{68F32EE2B50F8E58}" {
       m_eItemType BUILD
       m_iSupplyCost 1
      }
     }
    }
   }
  }
 }
}