SCR_EntityCatalogMultiList {
 m_aMultiLists {
  SCR_EntityCatalogMultiListEntry "{68EEFCCC0D7544C2}" {
   m_sIdentifier "Food"
   m_aEntities {
    SCR_EntityCatalogInventoryItem "{68EEFCCC0D7544F9}" {
     m_sEntityPrefab "{0021D6AEE15D1D30}Prefabs/FoodDrink/BirdEgg.et"
     m_aEntityDataList {
      FM_ArsenalItem "{68EEFCCC0D7544FB}" {
       m_eItemType FOOD
       m_iSupplyCost 1
       m_iMaxSpawn 3
      }
     }
    }
   }
  }
 }
}