SCR_EntityCatalogMultiList {
 m_aMultiLists {
  SCR_EntityCatalogMultiListEntry "{68EEFCCDD253DA02}" {
   m_sIdentifier "Food"
   m_aEntities {
    SCR_EntityCatalogInventoryItem "{68EEFCCDD253D5D9}" {
     m_sEntityPrefab "{5DC18BFBAA93C151}Prefabs/FoodDrink/Blueberry.et"
     m_aEntityDataList {
      FM_ArsenalItem "{68EEFCCDD253D5D8}" {
       m_eItemType FOOD
       m_iSupplyCost 1
       m_iMinSpawn 2
       m_iMaxSpawn 6
      }
     }
    }
    SCR_EntityCatalogInventoryItem "{68F368FCF08B3093}" {
     m_sEntityPrefab "{6FEC87C6B133A5F0}Prefabs/Props/Furniture/RequiredItems/stick.et"
     m_aEntityDataList {
      FM_ArsenalItem "{68F32EE2B50F8E58}" {
       m_eItemType BUILD
       m_iSupplyCost 1
      }
     }
    }
    SCR_EntityCatalogInventoryItem "{68F368FCF76EF803}" {
     m_sEntityPrefab "{CAC078FA37D4C95C}Prefabs/Props/Furniture/RequiredItems/Leaves.et"
     m_aEntityDataList {
      FM_ArsenalItem "{68F32EE2B50F8E58}" {
       m_eItemType BUILD
       m_iSupplyCost 1
       m_iMinSpawn 5
       m_iMaxSpawn 10
      }
     }
    }
   }
  }
 }
}