SCR_EntityCatalogMultiList {
 m_aMultiLists {
  SCR_EntityCatalogMultiListEntry "{68EEFCCDF628D24E}" {
   m_sIdentifier "Food"
   m_aEntities {
    SCR_EntityCatalogInventoryItem "{68EEFCCDF628D244}" {
     m_sEntityPrefab "{B00F6699B5E40D29}Prefabs/FoodDrink/Cabbage.et"
     m_aEntityDataList {
      FM_ArsenalItem "{68EEFCCDF628D246}" {
       m_eItemType FOOD
       m_iSupplyCost 1
      }
     }
    }
   }
  }
 }
}