SCR_EntityCatalogMultiList {
 m_aMultiLists {
  SCR_EntityCatalogMultiListEntry "{68EEFCCD873D1A6D}" {
   m_sIdentifier "Food"
   m_aEntities {
    SCR_EntityCatalogInventoryItem "{68EEFCCD873D1A6B}" {
     m_sEntityPrefab "{33B9574AD526D5AE}Prefabs/FoodDrink/Capsicum.et"
     m_aEntityDataList {
      FM_ArsenalItem "{68EEFCCD873D1A6A}" {
       m_eItemType FOOD
       m_iSupplyCost 1
       m_iMaxSpawn 2
      }
     }
    }
   }
  }
 }
}