SCR_EntityCatalogMultiList {
 m_aMultiLists {
  SCR_EntityCatalogMultiListEntry "{68EEFCCC6B5B502D}" {
   m_sIdentifier "Food"
   m_aEntities {
    SCR_EntityCatalogInventoryItem "{68EEFCCC6B5B5028}" {
     m_sEntityPrefab "{356AE47BFE19A47D}Prefabs/FoodDrink/ChickenEgg.et"
     m_aEntityDataList {
      FM_ArsenalItem "{68EEFCCC6B5B502A}" {
       m_eItemType FOOD
       m_iSupplyCost 1
       m_iMinSpawn 2
       m_iMaxSpawn 4
      }
     }
    }
   }
  }
 }
}