SCR_EntityCatalogMultiList {
 m_aMultiLists {
  SCR_EntityCatalogMultiListEntry "{68EEFCCC2C36C998}" {
   m_sIdentifier "Food"
   m_aEntities {
    SCR_EntityCatalogInventoryItem "{68EEFCCC2C36C991}" {
     m_sEntityPrefab "{D4D02A2479893CB7}Prefabs/FoodDrink/HoneyComb.et"
     m_aEntityDataList {
      FM_ArsenalItem "{68EEFCCC2C36C990}" {
       m_eItemType FOOD
       m_iSupplyCost 1
      }
     }
    }
   }
  }
 }
}