SCR_EntityCatalogMultiList {
 m_aMultiLists {
  SCR_EntityCatalogMultiListEntry "{68EEFCCCF5256EE9}" {
   m_sIdentifier "Food"
   m_aEntities {
    SCR_EntityCatalogInventoryItem "{68EEFCCCF5256EE7}" {
     m_sEntityPrefab "{439A037A2A45E6CF}Prefabs/FoodDrink/Mushroom.et"
     m_aEntityDataList {
      FM_ArsenalItem "{68EEFCCCF5256EE6}" {
       m_eItemType FOOD
       m_iSupplyCost 1
      }
     }
    }
   }
  }
 }
}