SCR_EntityCatalogMultiList {
 m_aMultiLists {
  SCR_EntityCatalogMultiListEntry "{68EEFCCC8BD768AF}" {
   m_sIdentifier "Food"
   m_aEntities {
    SCR_EntityCatalogInventoryItem "{68EEFCCC8BD768A5}" {
     m_sEntityPrefab "{6EB3ACE174E7244B}Prefabs/FoodDrink/Potato.et"
     m_aEntityDataList {
      FM_ArsenalItem "{68EEFCCC8BD768A4}" {
       m_eItemType FOOD
       m_iSupplyCost 1
       m_iMaxSpawn 2
      }
     }
    }
   }
  }
 }
}