SCR_EntityCatalogMultiList {
 m_aMultiLists {
  SCR_EntityCatalogMultiListEntry "{68EEFCCB53797F35}" {
   m_sIdentifier "Food"
   m_aEntities {
    SCR_EntityCatalogInventoryItem "{68EEFCCB53797F30}" {
     m_sEntityPrefab "{EB82B10E9C7D11A7}Prefabs/FoodDrink/Tomato.et"
     m_aEntityDataList {
      FM_ArsenalItem "{68EEFCCB53797F32}" {
       m_eItemType FOOD
       m_iSupplyCost 1
      }
     }
    }
   }
  }
 }
}