ADM_ShopConfig {
 m_Merchandise {
  ADM_ShopMerchandise "{693471005A74F776}" {
   m_Merchandise ADM_MerchandisePrefab "{693471005A74F74C}" {
    m_iMaxPurchaseQuantity 0
    m_iMaxSellQuantity 1
    m_sPrefab "{AAB632A193BF6B69}PrefabsEditable/Auto/Props/Civilian/Suspicious Items/E_WeedBrick.et"
   }
   m_BuyPayment {
    ADM_PaymentMethodCurrency "{69588DB383F6AE63}" {
     m_Quantity 1000
    }
   }
   m_SellPayment {
    ADM_PaymentMethodCurrency "{694754D813690DD8}" {
     m_Quantity 1000
    }
   }
  }
 }
}