ADM_ShopCategory {
 m_DisplayName "Backpacks"
 m_Items {
  "{9EF98EAACBC4353B}Prefabs/Items/Equipment/Backpacks/ACR Bag.et"
  "{11FC1F9DCFBABC34}Prefabs/Items/Equipment/Backpacks/Coyote Backpack.et"
  "{A896042C37533803}Prefabs/Items/Equipment/Backpacks/Coyote Patrol Pack.et"
  "{ACAAEC2F9DB11F03}Prefabs/Items/Equipment/Backpacks/Large Gun Bag.et"
  "{12321B761A982B49}Prefabs/Items/Equipment/Backpacks/Small Gun Bag.et"
  "{C2F5E3777430D199}Prefabs/Items/Equipment/Backpacks/TriZip BagMC.et"
  "{6063D4580366C999}Prefabs/Items/Equipment/Backpacks/TriZip BagBLK.et"
  "{52831FD5F93CC7C0}Prefabs/Items/Equipment/Backpacks/TriZip BagCoyote.et"
  "{F01F0A39E7F5CC8B}Prefabs/Items/Equipment/Backpacks/Backpack_MOTAR_CamelBag_70L.et"
  "{8F8E05E0E4A91625}Prefabs/Items/Equipment/Backpacks/Backpack_MOTAR_Military_M5.et"
  "{63ACC79491813E66}Prefabs/Items/Equipment/Backpacks/Backpack_MOTAR_Tactical_80L.et"
 }
}
