ADM_ShopCategory {
 m_DisplayName "Backpacks"
 m_Items {
  "{9EF98EAACBC4353B}Prefabs/Items/Equipment/Backpacks/ACR Bag.et"
  "{11FC1F9DCFBABC34}Prefabs/Items/Equipment/Backpacks/Coyote Backpack.et"
  "{A896042C37533803}Prefabs/Items/Equipment/Backpacks/Coyote Patrol Pack.et"
  "{ACAAEC2F9DB11F03}Prefabs/Items/Equipment/Backpacks/Large Gun Bag.et"
  "{12321B761A982B49}Prefabs/Items/Equipment/Backpacks/Small Gun Bag.et"
  "{C2F5E3777430D199}Prefabs/Items/Equipment/Backpacks/TriZip BagMC.et"
  "{6063D4580366C999}Prefabs/Items/Equipment/Backpacks/TriZip BagBLK.et"
  "{52831FD5F93CC7C0}Prefabs/Items/Equipment/Backpacks/TriZip BagCoyote.et"
  "{8F8E05E0E4A91625}Prefabs/Items/Equipment/Backpacks/Backpack_MOTAR_Military_M5.et"
  "{3DE0155EC9767B98}Prefabs/Items/Equipment/Backpacks/Backpack_Veshmeshok.et"
  "{443304F1EC50BC27}Prefabs/Items/Equipment/Backpacks/Backpack_Veshmeshok_Black.et"
  "{41A9C55B61F375F0}Prefabs/Items/Equipment/Backpacks/Backpack_Kolobok.et"
  "{4805E67E2AE30F8D}Prefabs/Items/Equipment/Backpacks/Backpack_Medical_M5.et"
  "{AC298BA8A7D27007}Prefabs/Items/Equipment/Backpacks/Backpack_Medical_Soviet_NoCross_01.et"
  "{FDA7B6630DB87991}Prefabs/Items/Equipment/Backpacks/Backpack_M70_Swiss.et"
  "{5C5C6EE05EE2FF1A}Prefabs/Items/Equipment/Backpacks/Backpack_ALICE_Medium_assembled.et"
  "{95D4766BBE46F23D}Prefabs/Items/Equipment/Backpacks/Backpack_IIFS_FieldPack.et"
  "{A870260CF6ECB936}Prefabs/Items/Equipment/Backpacks/Backpack_IIFS_FieldPack_hiking.et"
  "{499126BBC97FA228}Prefabs/Items/Equipment/Backpacks/Backpack_USMC_511_V2.et"
  "{E667138960943FED}Prefabs/Items/Equipment/Backpacks/Backpack_USMC_511_V2_M81.et"
 }
}
