ADM_ShopCategory {
 m_DisplayName "Ghillie"
 m_Items {
  "{3CF4BFED2574BA25}Clothing/Ghillie/Ghillie_Bottoms/Ghillie_Bottoms_Full/Ghillie Bottoms 1/Ghillie_Bottom_Full.et"
  "{C38A88D33732B97F}Clothing/Ghillie/Ghillie_Head/Ghillie head 1/Ghillie_Head.et"
  "{DAB3ABFC8EE4D8DB}Clothing/Ghillie/Ghillie_Top/Ghillie Top 1/Ghillie_Top.et"
 }
}