ADM_ShopCategory {
 m_DisplayName "Jackets"
 m_Items {
  "{BBA08EC4EC40FA94}Prefabs/Characters/Uniforms/Jacket_M70.et"
  "{9F546CCA2582D16F}Prefabs/Characters/Uniforms/Jacket_M88.et"
  "{D262D2102B9931C6}Prefabs/Characters/Uniforms/Jacket_M88_rolledup.et"
  "{F6C7806DBBF26C50}Prefabs/Characters/Uniforms/Jacket_M88_rolledup_TTsKO.et"
  "{ED9FFC8C35C98B8B}Prefabs/Characters/Uniforms/Jacket_M88_TTsKO.et"
  "{C7861F11D5334C0E}Prefabs/Characters/Uniforms/Jacket_US_BDU.et"
  "{293F577C298061E3}Prefabs/Characters/Uniforms/Jacket_US_BDU_02.et"
  "{3CCA7A9BB4FD3197}Prefabs/Characters/Uniforms/Jacket_US_BDU_rolledup.et"
  "{A080C1AEBF921DC4}Prefabs/Characters/Uniforms/Jacket_US_BDU_rolledup_02.et"
  "{86BBBEFE6A2F7B5A}Prefabs/Characters/Uniforms/Jacket_US_BDU_rolledup_TigerStripe.et"
  "{3D17E4FA8F819ECD}Prefabs/Characters/Uniforms/Jacket_US_BDU_TigerStripe.et"
  "{F1E29085C62F0D55}Prefabs/Characters/Uniforms/Jacket_KZS/Jacket_KZS.et"
  "{6835DAF42A09E23C}Prefabs/Characters/Uniforms/Jacket_Pilot_USSR_01/Jacket_Pilot_USSR_01.et"
  "{78C9B02C0CBD594C}Prefabs/Characters/Uniforms/Jacket_Tanker_USSR_01/Jacket_Tanker_USSR_01.et"
  "{CC2BAD4EACC9B2CA}Prefabs/Characters/Uniforms/Jacket_TAZ83/Jacket_TAZ83_01.et"
 }
}