ADM_ShopCategory {
 m_DisplayName "Pants"
 m_Items {
  "{06BC3F18B47799AE}Prefabs/Characters/Uniforms/Pants_M70.et"
  "{4DC4FD2F6D353B12}Prefabs/Characters/Uniforms/Pants_M70_Dirty.et"
  "{DCF980831E880F6A}Prefabs/Characters/Uniforms/Pants_M88.et"
  "{7E45E8E203507300}Prefabs/Characters/Uniforms/Pants_M88_TTsKO.et"
  "{604BB72BE8E023C2}Prefabs/Characters/Uniforms/Pants_US_BDU.et"
  "{C6BE0A871E7DE807}Prefabs/Characters/Uniforms/Pants_US_BDU_TigerStripe.et"
  "{86BB79B9A2233780}Prefabs/Characters/Uniforms/Pants_US_M65.et"
  "{5E17C1AE66A6FF00}Prefabs/Characters/Uniforms/Pants_KZS/Pants_KZS.et"
  "{83DFA8F68CA40B10}Prefabs/Characters/Uniforms/Pants_Pilot_USSR_01/Pants_Pilot_USSR_01.et"
  "{6B7F32F1F8A191B0}Prefabs/Characters/Uniforms/Pants_Pilot_USSR_01/Pants_Pilot_USSR_01_tucked.et"
  "{27494A16F172A97B}Prefabs/Characters/Uniforms/Pants_Tanker_USSR_01/Pants_Tanker_USSR_01.et"
  "{DC91A67E1074AAC0}Prefabs/Characters/Uniforms/Pants_Tanker_USSR_01/Pants_Tanker_USSR_01_tucked.et"
  "{27364244288DA83B}Prefabs/Characters/Uniforms/Pants_TAZ83/Pants_TAZ83_01.et"
 }
}