ADM_ShopCategory {
 m_DisplayName "Police Uniform"
 m_Items {
  "{4AB95C821AFEAD58}Clothing/Rus_Police Man/Pants/Police Pants.et"
  "{05F042A3599FEED7}Clothing/Rus_Police Man/Jacket/Police jacket.et"
  "{98841059F2166DAC}Clothing/Rus_Police Man/Hat/Police Hat.et"
 }
}