SCR_EntityCatalogMultiList {
 m_aMultiLists {
  SCR_EntityCatalogMultiListEntry "{B706000000002001}" {
   m_sIdentifier "Caixas de Madeira - Materiais"
   m_aEntities {
    SCR_EntityCatalogInventoryItem "{B706000000002002}" {
     m_sEntityPrefab "{D7DC4E6EE61E99C1}Prefabs/Props/Furniture/RequiredItems/ToolKit.et"
     m_aEntityDataList {
      FM_ArsenalItem "{B706000000002003}" {
       m_eItemType BUILD
       m_iSupplyCost 5
       m_iMinSpawn 0
      }
     }
    }
    SCR_EntityCatalogInventoryItem "{B706000000002004}" {
     m_sEntityPrefab "{D7DC4E6EE61E99C1}Prefabs/Props/Furniture/RequiredItems/ToolKit.et"
     m_aEntityDataList {
      FM_ArsenalItem "{B706000000002005}" {
       m_eItemType BUILD
       m_iSupplyCost 5
       m_iMinSpawn 0
      }
     }
    }
    SCR_EntityCatalogInventoryItem "{B706000000002006}" {
     m_sEntityPrefab "{05562DD0D7651987}Prefabs/Items/Equipment/Kits/RepairKit_01/RepairKitFM.et"
     m_aEntityDataList {
      FM_ArsenalItem "{B706000000002007}" {
       m_eItemType TOOLS
       m_iSupplyCost 3
       m_iMinSpawn 0
      }
     }
    }
    SCR_EntityCatalogInventoryItem "{B706000000002008}" {
     m_sEntityPrefab "{05562DD0D7651987}Prefabs/Items/Equipment/Kits/RepairKit_01/RepairKitFM.et"
     m_aEntityDataList {
      FM_ArsenalItem "{B706000000002009}" {
       m_eItemType TOOLS
       m_iSupplyCost 3
       m_iMinSpawn 0
      }
     }
    }
    SCR_EntityCatalogInventoryItem "{B70600000000200A}" {
     m_sEntityPrefab "{E7DF31108D38A8A8}Prefabs/Items/Fuel/Jerrycan_01/Jerrycan_01_item_base.et"
     m_aEntityDataList {
      FM_ArsenalItem "{B70600000000200B}" {
       m_eItemType VEHICLE
       m_iSupplyCost 5
       m_iMinSpawn 0
      }
     }
    }
   }
  }
 }
}
