SCR_EntityCatalogMultiList {
 m_aMultiLists {
  SCR_EntityCatalogMultiListEntry "{B706000000003001}" {
   m_sIdentifier "Caixa de Papelao - Materiais"
   m_aEntities {
    SCR_EntityCatalogInventoryItem "{B706000000003002}" {
     m_sEntityPrefab "{D7DC4E6EE61E99C1}Prefabs/Props/Furniture/RequiredItems/ToolKit.et"
     m_aEntityDataList {
      FM_ArsenalItem "{B706000000003003}" {
       m_eItemType BUILD
       m_iSupplyCost 5
       m_iMinSpawn 0
      }
     }
    }
    SCR_EntityCatalogInventoryItem "{B706000000003004}" {
     m_sEntityPrefab "{05562DD0D7651987}Prefabs/Items/Equipment/Kits/RepairKit_01/RepairKitFM.et"
     m_aEntityDataList {
      FM_ArsenalItem "{B706000000003005}" {
       m_eItemType TOOLS
       m_iSupplyCost 3
       m_iMinSpawn 0
      }
     }
    }
    SCR_EntityCatalogInventoryItem "{B706000000003006}" {
     m_sEntityPrefab "{05562DD0D7651987}Prefabs/Items/Equipment/Kits/RepairKit_01/RepairKitFM.et"
     m_aEntityDataList {
      FM_ArsenalItem "{B706000000003007}" {
       m_eItemType TOOLS
       m_iSupplyCost 3
       m_iMinSpawn 0
      }
     }
    }
    SCR_EntityCatalogInventoryItem "{B706000000003008}" {
     m_sEntityPrefab "{575EA58E67448C2A}Prefabs/Items/Equipment/Flashlights/Flashlight_Soviet_01/Flashlight_Soviet_01.et"
     m_aEntityDataList {
      FM_ArsenalItem "{B706000000003009}" {
       m_eItemType EQUIPMENT
       m_iSupplyCost 2
       m_iMinSpawn 0
      }
     }
    }
    SCR_EntityCatalogInventoryItem "{B70600000000300A}" {
     m_sEntityPrefab "{27FCA0F311B3559C}Prefabs/Weapons/Attachments/Flashlight/Tapelight.et"
     m_aEntityDataList {
      FM_ArsenalItem "{B70600000000300B}" {
       m_eItemType EQUIPMENT
       m_iSupplyCost 3
       m_iMinSpawn 0
      }
     }
    }
   }
  }
 }
}
