SCR_EntityCatalogMultiList {
 m_aMultiLists {
  SCR_EntityCatalogMultiListEntry "{B704000000002001}" {
   m_sIdentifier "Rare Military Gear"
   m_aEntities {
    SCR_EntityCatalogInventoryItem "{B704000000002002}" {
     m_sEntityPrefab "{499126BBC97FA228}Prefabs/Items/Equipment/Backpacks/Backpack_USMC_511_V2.et"
     m_aEntityDataList {
      FM_ArsenalItem "{B704000000002003}" {
       m_eItemType BACKPACK
       m_iSupplyCost 4
      }
     }
    }
    SCR_EntityCatalogInventoryItem "{B704000000002004}" {
     m_sEntityPrefab "{07223CB6B9212D8A}Prefabs/Characters/Vests/Vest_JPC/Vest_JPC_AOR2.et"
     m_aEntityDataList {
      FM_ArsenalItem "{B704000000002005}" {
       m_eItemType VEST_AND_WAIST
       m_iSupplyCost 4
      }
     }
    }
    SCR_EntityCatalogInventoryItem "{B704000000002006}" {
     m_sEntityPrefab "{3E5331420D90BBEB}Prefabs/Characters/Vests/Vest_TV102/Vest_TV102_EMR_Desert.et"
     m_aEntityDataList {
      FM_ArsenalItem "{B704000000002007}" {
       m_eItemType VEST_AND_WAIST
       m_iSupplyCost 4
      }
     }
    }
    SCR_EntityCatalogInventoryItem "{B704000000002008}" {
     m_sEntityPrefab "{B76EAFDBFBA131D9}Prefabs/Characters/HeadGear/Helmets/Helmet_OPSCORE/WCS_Variants/Helmet_OPSCORE_XP_Standard_Issue.et"
     m_aEntityDataList {
      FM_ArsenalItem "{B704000000002009}" {
       m_eItemType HEADWEAR
       m_iSupplyCost 4
      }
     }
    }
    SCR_EntityCatalogInventoryItem "{B70400000000200A}" {
     m_sEntityPrefab "{B74A4FF0DD8BB116}Prefabs/Characters/HeadGear/Helmets/Helmet_PASGT/Helmet_PASGT_01.et"
     m_aEntityDataList {
      FM_ArsenalItem "{B70400000000200B}" {
       m_eItemType HEADWEAR
       m_iSupplyCost 4
      }
     }
    }
   }
  }
 }
}
