SCR_EntityCatalogMultiList {
 m_aMultiLists {
  SCR_EntityCatalogMultiListEntry "{B704000000002001}" {
   m_sIdentifier "Delegacia Desk Utility"
   m_aEntities {
    SCR_EntityCatalogInventoryItem "{B704000000002002}" {
     m_sEntityPrefab "{4762ACD5C5F24B06}Prefabs/Items/Medicine/Bandage.et"
     m_aEntityDataList {
      FM_ArsenalItem "{B704000000002003}" {
       m_eItemType HEAL
       m_eItemMode CONSUMABLE
       m_iSupplyCost 2
       m_iMinSpawn 0
      }
     }
    }
    SCR_EntityCatalogInventoryItem "{B704000000002004}" {
     m_sEntityPrefab "{3BD9B80FAAF5E8B5}Prefabs/Items/Medicine/Gauze.et"
     m_aEntityDataList {
      FM_ArsenalItem "{B704000000002005}" {
       m_eItemType HEAL
       m_eItemMode CONSUMABLE
       m_iSupplyCost 2
       m_iMinSpawn 0
      }
     }
    }
    SCR_EntityCatalogInventoryItem "{B704000000002006}" {
     m_sEntityPrefab "{F79E65E3094DD0D5}Prefabs/Items/Medicine/FieldDressing_USSR.et"
     m_aEntityDataList {
      FM_ArsenalItem "{B704000000002007}" {
       m_eItemType HEAL
       m_eItemMode CONSUMABLE
       m_iSupplyCost 3
       m_iMinSpawn 0
      }
     }
    }
    SCR_EntityCatalogInventoryItem "{B704000000002008}" {
     m_sEntityPrefab "{73A58C5DF4882D01}Prefabs/Weapons/Attachments/Optics/Radius_RangeFinder_RIS.et"
     m_aEntityDataList {
      FM_ArsenalItem "{B704000000002009}" {
       m_eItemType EQUIPMENT
       m_iSupplyCost 12
       m_iMinSpawn 0
      }
     }
    }
   }
  }
 }
}
