SCR_EntityCatalogMultiList {
 m_aMultiLists {
  SCR_EntityCatalogMultiListEntry "{3872918C0EC3B281}" {
   m_sIdentifier "Delegacia Desk Utility"
   m_aEntities {
    SCR_EntityCatalogInventoryItem "{3872918C0EC3B282}" {
     m_sEntityPrefab "{6BADCDCC0DFE2401}Prefabs/Items/Medicine/FieldDressing_01/Bandage.et"
     m_aEntityDataList {
      FM_ArsenalItem "{3872918C0EC3B283}" {
       m_iSupplyCost 1
      }
     }
    }
    SCR_EntityCatalogInventoryItem "{3872918C0EC3B284}" {
     m_sEntityPrefab "{B06C6EFC0BEAEFD1}Prefabs/Items/Medicine/FieldDressing_01/Gauze_01.et"
     m_aEntityDataList {
      FM_ArsenalItem "{3872918C0EC3B285}" {
       m_iSupplyCost 1
      }
     }
    }
    SCR_EntityCatalogInventoryItem "{3872918C0EC3B286}" {
     m_sEntityPrefab "{C3F1FA1E2EC2B345}Prefabs/Items/Medicine/FieldDressing_01/FieldDressing_USSR_01.et"
     m_aEntityDataList {
      FM_ArsenalItem "{3872918C0EC3B287}" {
       m_iSupplyCost 1
      }
     }
    }
    SCR_EntityCatalogInventoryItem "{3872918C0EC3B288}" {
     m_sEntityPrefab "{BBE1F3AD25BB00EF}Prefabs/Weapons/Attachments/RangeFinder/Radius_RangeFinder_RIS.et"
     m_aEntityDataList {
      FM_ArsenalItem "{3872918C0EC3B289}" {
       m_iSupplyCost 6
      }
     }
    }
   }
  }
 }
}
