SCR_EntityCatalogMultiList {
 m_aMultiLists {
  SCR_EntityCatalogMultiListEntry "{68F01D0D2A3A0001}" {
   m_sIdentifier "Military Weapons"
   m_aEntities {
    SCR_EntityCatalogInventoryItem "{68F01D0D2A3A0002}" {
     m_sEntityPrefab "{6545DEABED4759E5}Prefabs/Weapons/Rifles/Mosin/BC_Rifle_Mosin_Nagant_9130_PU.et"
     m_aEntityDataList {
      FM_ArsenalItem "{68F01D0D2A3A0003}" {
       m_eItemType SNIPER_RIFLE
       m_eItemMode WEAPON
       m_iSupplyCost 4
      }
     }
    }
    SCR_EntityCatalogInventoryItem "{68F01D0D2A3A0004}" {
     m_sEntityPrefab "{053B975DDBCAF1B0}Prefabs/Weapons/Rifles/556/Rifle_AUG_base.et"
     m_aEntityDataList {
      FM_ArsenalItem "{68F01D0D2A3A0005}" {
       m_eItemMode WEAPON
       m_iSupplyCost 3
      }
     }
    }
   }
  }
  SCR_EntityCatalogMultiListEntry "{68F01D0D2A3A0006}" {
   m_sIdentifier "Military Magazines"
   m_aEntities {
    SCR_EntityCatalogInventoryItem "{68F01D0D2A3A0007}" {
     m_sEntityPrefab "{76AB02261CF11947}Prefabs/Weapons/Magazines/556/Magazine_556x45_STANAG_40rnd_AUG_M193_.et"
     m_aEntityDataList {
      FM_ArsenalItem "{68F01D0D2A3A0008}" {
       m_eItemMode AMMUNITION
       m_iSupplyCost 3
      }
     }
    }
   }
  }
 }
}
