PersistenceSystemConfig : "{5BA7C4643477E2D7}Configs/Systems/Persistence/EditableMission.conf" {
 Configurations {
  PersistenceConfigGroup Entities {
   Configurations {
    PersistenceConfigGroup Items {
     Configurations {
      EntityPersistenceConfig "{64CAFB94F1A3338C}" {
       Rule PrefabPersistenceConfigRule "{64F09C88C714F0E9}" {
        Prefabs +{
         "{F539F8AD9A0D2249}Prefabs/Items/WalletFisicalValue.et"
         "{2730C123BE8FA101}Prefabs/Items/WalletVirtualValue.et"
         "{9A7C8A96853B03B6}Prefabs/Items/1000dol.et"
         "{0DAB239CAC6D40BF}Prefabs/Items/500dol.et"
         "{1A7C2C830126AA67}Prefabs/Items/100dol.et"
         "{C3A8AF077A97A7A6}Prefabs/Items/10dol.et"
         "{1A32E3232C7C5619}Prefabs/Items/1dol.et"
         "{717FEDEC2535943E}Prefabs/Items/20dol.et"
         "{386CB78806FA2B15}Prefabs/Items/50dol.et"
         "{6F6B6A2281DE4D6D}Prefabs/Items/5dol.et"
        }
       }
      }
     }
    }
   }
  }
 }
}
