SCR_MissionHeaderCombatOps {
 World "{89446B179FB7D077}Worlds/chernarus.ent"
 SystemsConfig "{8DDC2A311929D52F}Configs/Systems/GameMasterSystems.conf"
 m_sName "BrasilZ"
 m_sAuthor "Mateus"
 m_sIcon "{B4EC71B0647994BF}UI/Images/pre.edds"
 m_sLoadingScreen "{CF459B79E65A7B58}UI/Images/carregando.edds"
 m_sPreviewImage "{B4EC71B0647994BF}UI/Images/pre.edds"
 m_sGameMode "Survival"
 m_iPlayerCount 120
 m_eSaveTypes 7
 m_eEditableGameFlags 7
 m_eDefaultGameFlags 7
 m_bOverrideScenarioTimeAndWeather 1
}
