SCR_MissionHeader {
 World "{1DF5E9C75A8714E7}Worlds/GM_Cherno/GM_Cherno.ent"
 SystemsConfig "{8DDC2A311929D52F}Configs/Systems/GameMasterSystems.conf"
 m_sName "BrasilZ Game Master"
 m_sAuthor "Mateus"
 m_sDescription "Game Master scenario for BrasilZ on Chernarus."
 m_sGameMode "GameMaster"
 m_iPlayerCount 120
 m_bOverrideScenarioTimeAndWeather 1
}
