ADM_ShopCategory {
 m_DisplayName "SUV"
 m_Items {
  "{34D6A01EC0631C72}Prefabs/Vehicles/Wheeled/SUV/SUV_Black.et"
  "{A254F0204D10469C}Prefabs/Vehicles/Wheeled/SUV/SUV_Blue.et"
  "{323E579ACFEB3BDB}Prefabs/Vehicles/Wheeled/SUV/SUV_Green.et"
  "{789F83AC2C6237E3}Prefabs/Vehicles/Wheeled/SUV/SUV_Grey.et"
  "{2756A08FF7F8CA45}Prefabs/Vehicles/Wheeled/SUV/SUV_Lime.et"
  "{4D19CFDE6427E608}Prefabs/Vehicles/Wheeled/SUV/SUV_new_Base.et"
  "{00AEB358AD35C9C9}Prefabs/Vehicles/Wheeled/SUV/SUV_Orange.et"
  "{0D5199C17633BDB5}Prefabs/Vehicles/Wheeled/SUV/SUV_Red.et"
 }
}