ADM_ShopCategory {
 m_Items {
  "{760C2ED4B68431D3}Prefabs/Vehicles/Wheeled/Ural4320/Ural4320_01.et"
  "{6574DA63A320F7FE}Prefabs/Vehicles/Wheeled/Ural4320/Ural4320_blue_01.et"
  "{3426AE1ACA70787B}Prefabs/Vehicles/Wheeled/Ural4320/Ural4320_JZD_01.et"
  "{597D557BE85D9DED}Prefabs/Vehicles/Wheeled/Ural4320/Ural4320C_orange_01.et"
 }
}